classdef tExampleGallery < matlab.unittest.TestCase
%tExampleGallery Keeps the HTML Examples gallery in sync with examples/.
%
%   phx/doc/phx_ex_gallery.html is generated by tools/buildExampleDocs.m from
%   the phxex_* examples. Nothing forces anyone to re-run that generator after
%   adding, renaming or deleting a demo, so these tests do: they fail when the
%   gallery, its thumbnails or the table of contents drift away from what is
%   actually in examples/.
%
%   Pure tests - no engine, no graphics.
%
%   See also tSkillsPackaged, buildExampleDocs

%   Copyright 2026 HUMUSOFT s.r.o.

    properties (Constant)
        Gallery = fullfile("phx", "doc", "phx_ex_gallery.html")
        Toc = fullfile("phx", "doc", "helptoc.xml")
        ThumbDir = fullfile("phx", "doc", "img", "ex")
    end

    properties
        Root
        Names       % the phxex_* files in examples/
        Html        % content of the generated gallery
    end

    methods (TestClassSetup)
        function locateRoot(tc)
            tc.Root = string(fileparts(fileparts(mfilename("fullpath"))));
            tc.assumeTrue(isfolder(fullfile(tc.Root, "examples")), ...
                "Examples folder not found - not a source checkout.");
            tc.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(tc.Root, "tools")));       % for exampleCatalog

            % Every phxex_*.m belongs in the gallery; a phxex_*.slx only when
            % exampleCatalog gives it a caption (see buildExampleDocs).
            files = dir(fullfile(tc.Root, "examples", "phxex_*.m"));
            names = string(erase({files.name}, ".m"));
            models = dir(fullfile(tc.Root, "examples", "phxex_*.slx"));
            catalog = exampleCatalog;
            described = catalog.Name(catalog.Summary ~= "");
            tc.Names = sort([names, intersect(string(erase({models.name}, ".slx")), described')]);
            tc.assumeNotEmpty(tc.Names, "No phxex_* examples found.");

            tc.assertTrue(isfile(fullfile(tc.Root, tc.Gallery)), ...
                tc.Gallery + " is missing - run tools/buildExampleDocs.");
            tc.Html = string(fileread(fullfile(tc.Root, tc.Gallery)));
        end
    end

    methods (Test)
        function everyExampleHasATile(tc)
            missing = tc.Names(~arrayfun(@(n) contains(tc.Html, ...
                """phx-tile-cmd"">" + n + "<"), tc.Names));
            tc.verifyEmpty(missing, "Not in the gallery: " + join(missing, ", ") + ...
                ". Re-run tools/buildExampleDocs.");
        end

        function everyTileHasAnExample(tc)
            listed = sort(unique(string(regexp(tc.Html, ...
                '(?<="phx-tile-cmd">)phxex_\w+', "match"))));
            stale = setdiff(listed, tc.Names);
            tc.verifyEmpty(stale, "Gallery lists examples that no longer exist: " + ...
                join(stale, ", ") + ". Re-run tools/buildExampleDocs.");
        end

        function everyExampleHasAThumbnail(tc)
            missing = tc.Names(~arrayfun(@(n) ...
                isfile(fullfile(tc.Root, tc.ThumbDir, n + ".png")), tc.Names));
            tc.verifyEmpty(missing, "No thumbnail for: " + join(missing, ", ") + ...
                ". Run tools/buildExampleDocs (it captures the missing ones).");
        end

        function thumbnailsAreReferencedAndUniform(tc)
            % A stale thumbnail of a deleted demo silently bloats the .mltbx,
            % and an odd-sized one breaks the grid layout.
            files = dir(fullfile(tc.Root, tc.ThumbDir, "*.png"));
            names = string({files.name});
            unused = names(~arrayfun(@(f) contains(tc.Html, "img/ex/" + f), names));
            tc.verifyEmpty(unused, "Thumbnails the gallery does not use: " + ...
                join(unused, ", ") + ". Re-run tools/buildExampleDocs, or delete " + ...
                "them if their examples are gone.");

            pixels = zeros(numel(files), 2);
            for k = 1:numel(files)
                info = imfinfo(fullfile(tc.Root, tc.ThumbDir, files(k).name));
                pixels(k, :) = [info.Width info.Height];
            end
            tc.verifySize(unique(pixels, "rows"), [1 2], ...
                "The thumbnails do not all have the same size.");
        end

        function tocPointsAtTheGallery(tc)
            toc = string(fileread(fullfile(tc.Root, tc.Toc)));
            tc.verifySubstring(toc, "phx_ex_gallery.html", ...
                "helptoc.xml does not list the Examples gallery.");

            generated = extractBetween(toc, "<!-- BEGIN generated by tools/buildExampleDocs.m -->", ...
                "<!-- END generated -->");
            tc.assertNotEmpty(generated, "The generated block of helptoc.xml is gone.");
            tc.verifySubstring(generated(1), "<tocitem", ...
                "The generated block of helptoc.xml is empty - run tools/buildExampleDocs.");

            % Every section anchor of the toc must exist in the gallery.
            anchors = string(regexp(generated(1), '(?<=phx_ex_gallery\.html#)[\w-]+', "match"));
            for a = anchors
                tc.verifySubstring(tc.Html, "id=""" + a + """", ...
                    "helptoc.xml links to #" + a + ", which the gallery does not define.");
            end
        end

        function docPagesDoNotLinkToDeletedTopics(tc)
            % The gallery replaced the old "Examples and larger scenes" topic;
            % a leftover link to it would be a dead end in the Help Browser.
            pages = dir(fullfile(tc.Root, "phx", "doc", "*.html"));
            for p = string({pages.name})
                text = string(fileread(fullfile(tc.Root, "phx", "doc", p)));
                targets = unique(string(regexp(text, '(?<=href=")[^"#:]+\.html', "match")));
                for t = targets
                    tc.verifyTrue(isfile(fullfile(tc.Root, "phx", "doc", t)), ...
                        p + " links to " + t + ", which does not exist.");
                end
            end
        end
    end

end
