classdef tStoredState < PhxTestCase
%tStoredState Tests for the kinematic state store of phx.Body.
%
%   storeState / restoreState / clearStates keep named snapshots of pose,
%   linear and angular velocity. The same transfer is used internally
%   whenever a body crosses an engine boundary: initObject carries the
%   state into a freshly created engine body, and phx.Simulation reads it
%   out and writes it back when the world is torn down. That is what makes
%   a body keep its velocity when it is put into a simulation, when the
%   simulation is deleted and when it is added to a new one.
%
%   The API tests need no engine - the properties fall back to their
%   MATLAB-side values while a body has no engine handle - but a body owns
%   an hgtransform, so they carry the "Graphics" tag. The transfer tests
%   run a real world and carry "Engine".
%
%   See also phx.Body.storeState, phx.Body.restoreState, phx.Body.clearStates

%   Copyright 2026 HUMUSOFT s.r.o.

    methods (Test, TestTags = {'Graphics'})
        function storeRestoreRoundTripsPoseAndVelocity(tc)
            % All four pieces of the kinematic state come back.
            b = tc.spawnBody([1 2 3]);
            b.EulerAngles = [0.2 -0.3 0.5];
            b.LinearVelocity = [4 5 6];
            b.AngularVelocity = [0.7 0.8 0.9];
            T = b.Transform;
            b.storeState("snapshot");

            b.Position = [-9 -9 -9];
            b.EulerAngles = [0 0 0];
            b.LinearVelocity = [0 0 0];
            b.AngularVelocity = [0 0 0];

            b.restoreState("snapshot");

            tc.verifyEqual(b.Transform, T, "AbsTol", 1e-12);
            tc.verifyEqual(b.LinearVelocity, [4 5 6], "AbsTol", 1e-12);
            tc.verifyEqual(b.AngularVelocity, [0.7 0.8 0.9], "AbsTol", 1e-12);
        end

        function autoGeneratedStateNamesAreSequential(tc)
            b = tc.spawnBody([0 0 0]);
            tc.verifyEqual(b.storeState, "state1");
            tc.verifyEqual(b.storeState, "state2");
        end

        function restoreDefaultsToTheLastStoredState(tc)
            b = tc.spawnBody([0 0 0]);
            b.storeState;                 % state1 at the origin
            b.Position = [5 0 0];
            b.storeState;                 % state2 at [5 0 0]
            b.Position = [7 7 7];

            tc.verifyEqual(b.restoreState, "state2");
            tc.verifyEqual(b.Position, [5 0 0], "AbsTol", 1e-12);
        end

        function namedStateIsRestoredIndependentlyOfOrder(tc)
            b = tc.spawnBody([0 0 0]);
            b.storeState("first");
            b.Position = [5 0 0];
            b.storeState("second");

            b.restoreState("first");
            tc.verifyEqual(b.Position, [0 0 0], "AbsTol", 1e-12);
            b.restoreState("second");
            tc.verifyEqual(b.Position, [5 0 0], "AbsTol", 1e-12);
        end

        function clearStatesRemovesEverything(tc)
            b = tc.spawnBody([0 0 0]);
            b.storeState("first");
            b.storeState("second");
            b.Position = [1 1 1];

            b.clearStates;

            % Nothing left to restore, and the pose is left alone.
            tc.verifyEmpty(b.restoreState);
            tc.verifyEqual(b.Position, [1 1 1], "AbsTol", 1e-12);
        end

        function clearStatesRemovesOnlyTheNamedState(tc)
            b = tc.spawnBody([0 0 0]);
            b.storeState("first");
            b.Position = [5 0 0];
            b.storeState("second");
            b.Position = [9 9 9];

            b.clearStates("first");

            tc.verifyEqual(b.restoreState, "second");
            tc.verifyEqual(b.Position, [5 0 0], "AbsTol", 1e-12);
        end

        function statesAreStoredPerBody(tc)
            % One call stores a state on every given body, each holding its
            % own pose under the shared name.
            bodies = [tc.spawnBody([1 0 0]) tc.spawnBody([2 0 0])];
            storeState(bodies, "start");

            bodies(1).Position = [0 0 5];
            bodies(2).Position = [0 0 6];
            restoreState(bodies, "start");

            tc.verifyEqual(bodies(1).Position, [1 0 0], "AbsTol", 1e-12);
            tc.verifyEqual(bodies(2).Position, [2 0 0], "AbsTol", 1e-12);
        end
    end

    methods (Test, TestTags = {'Engine'})
        function velocitySetBeforeInitializationReachesTheEngine(tc)
            % A velocity assigned while the body has no engine handle is
            % carried into the engine body that initObject creates.
            tc.requireEngine;
            b = tc.spawnBody([0 0 50]);
            b.LinearVelocity = [5 0 0];

            sim = phx.Simulation(b, "Gravity", [0 0 0]);
            tc.addTeardown(@() delete(sim));

            % Read back through the engine now that the body is registered.
            tc.verifyEqual(b.LinearVelocity, [5 0 0], "AbsTol", 1e-9);

            sim.step(0.5, 50, -1);
            tc.verifyEqual(b.Position, [2.5 0 50], "AbsTol", 1e-6);
        end

        function poseAndVelocitySurviveSimulationTeardown(tc)
            % phx.Simulation.destroyObject reads the state out of the world
            % before clearing it and writes it back, so a body can be moved
            % to a new simulation and carry on from where it stopped.
            tc.requireEngine;
            b = tc.spawnBody([0 0 50]);
            sim = phx.Simulation(b, "Gravity", [0 0 0]);
            b.LinearVelocity = [1 2 3];
            b.AngularVelocity = [0 0 4];
            sim.step(0.5, 50, -1);
            pos = b.Position;

            delete(sim);
            tc.verifyEqual(b.Position, pos, "AbsTol", 1e-12);
            tc.verifyEqual(b.LinearVelocity, [1 2 3], "AbsTol", 1e-6);
            tc.verifyEqual(b.AngularVelocity, [0 0 4], "AbsTol", 1e-6);

            sim2 = phx.Simulation(b, "Gravity", [0 0 0]);
            tc.addTeardown(@() delete(sim2));
            tc.verifyEqual(b.LinearVelocity, [1 2 3], "AbsTol", 1e-6);

            sim2.step(0.5, 50, -1);
            tc.verifyEqual(b.Position, pos + [0.5 1 1.5], "AbsTol", 1e-6);
        end

        function restoreStateMidRunWritesThroughToTheEngine(tc)
            % Restoring while the world is alive must not only refresh the
            % MATLAB-side values: the engine has to see them too.
            tc.requireEngine;
            b = tc.spawnBody([0 0 50]);
            b.LinearVelocity = [3 0 0];
            sim = phx.Simulation(b, "Gravity", [0 0 -9.81]);
            tc.addTeardown(@() delete(sim));
            b.storeState("launch");

            sim.step(0.5, 50, -1);
            tc.verifyLessThan(b.Position(3), 50);

            b.restoreState("launch");

            tc.verifyEqual(b.Position, [0 0 50], "AbsTol", 1e-9);
            tc.verifyEqual(b.LinearVelocity, [3 0 0], "AbsTol", 1e-9);
        end

        function restoreStateReplaysTheSameTrajectory(tc)
            % Pose plus velocity fully determine what a free body does next,
            % so a restored run reproduces the first one (the determinism
            % guarantee tSimulation locks in for whole worlds).
            tc.requireEngine;
            b = tc.spawnBody([0 0 50]);
            b.LinearVelocity = [2 -1 0];
            b.AngularVelocity = [0.5 0 0.2];
            sim = phx.Simulation(b);
            tc.addTeardown(@() delete(sim));
            b.storeState("launch");

            sim.step(0.5, 50, -1);
            first = b.Transform;

            b.restoreState("launch");
            sim.step(0.5, 50, -1);

            tc.verifyEqual(b.Transform, first, "AbsTol", 1e-12);
        end
    end

end
